language: "sh"

sudo: "required"

branches:
  only:
    - qa/0.x
    - /^stable\/\d+\.\d+\.x$/

addons:
  apt:
    packages:
      - python-pip
      - p7zip-full
      - unar

services:
  - "docker"

dist: "trusty"

branches:
  only:
    - "wellcome-storage-service"

env:
  matrix:
    - "IMAGE=storage_service"

before_install:
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in secrets.zip.enc -out secrets.zip -d
  - unzip -d ~/.aws secrets.zip

script:
  >
    if [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      make "$IMAGE-publish"
    else
      make "$IMAGE-build"
    fi

notifications:
  email:
    - "wellcomedigitalplatform@wellcome.ac.uk"

matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=linting
    - python: "2.7"
      env: TOXENV=checkformigrations
  allow_failures:
    - python: "3.6"
      env: TOXENV=py36
