language: "sh"

sudo: "required"

branches:
  only:
    - "wellcome-storage-service"

addons:
  apt:
    packages:
      - python-pip
      - p7zip-full
      - unar

services:
  - "docker"

dist: "trusty"

env:
  matrix:
    - "IMAGE=storage_service"

before_install:
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in secrets.zip.enc -out secrets.zip -d
  - unzip -d ~/.aws secrets.zip

script:
  >
    if [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      make "$IMAGE-publish"
    else
      make "$IMAGE-build"
    fi

notifications:
  email:
    - "wellcomedigitalplatform@wellcome.ac.uk"
